
name: "Workflow Practice"
on:
  - push:
      branches:
        - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
       - name: "Step1 Running"
         run: echo " Studying for Devops Quiz " 
     
