


name: Workflow pratice
on:
  push:
    branches:
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Echoing content"
        run: echo "Hello World from Umer Riaz"
