name: First Workflow 
on:
  push:
    branches:
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "printing content using Github actions"
        run: echo "Umer Riaz"
